### ISSUE TITLE
Align sim-swap notification subscription Yaml with new subscription model

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/SimSwap#108]
**Problem description**
Decision at commonalities level is to shift to CloudEvents model.
Template & documentation are provided.

**Expected behavior**
Modifiy [sim-swap-notification-subscription.yaml](https://github.com/camaraproject/SimSwap/blob/main/code/API_definitions/sim-swap-notification-subscription.yaml) accordingly to this new format.

**Alternative solution**

**Additional context**
To be done for the first meta release

**Comment by gregory1g** [comment]
What is a difference between the current design which is already CloudEvent based (in the master branch) and the "new format"?

Side not: 
current spec includes the following notification event example:

> examples:
    SWAPPED:
      value:
        id: '123655'
        source: supertelco.notificationSendServer12
        type: org.camaraproject.sim-swap.v0.swapped
        specversion: '1.0'
        datacontenttype: application/json
        data:
          **phoneNumber: 123456788**
          subscriptionId: 2ghy-55gg-7iup-yuo9
        time: 2023-01-18T13:18:23.682Z
    SUBSCRIPTION_ENDS:
      value:
        id: '123658'
        source: supertelco.notificationSendServer12
        type: org.camaraproject.sim-swap.v0.subscription-ends
        specversion: '1.0'
        datacontenttype: application/json
        data:
          **phoneNumber: 123456789**
          terminationReason: SUBSCRIPTION_EXPIRED
          subscriptionId: 2ghy-55gg-7iup-yuo9
          terminationDescription: subscription expire time reached
        time: 2023-01-19T13:18:23.682Z


As far as I understand phoneNumber must be a string and include leading "+", like 
phoneNumber: <b>"+</b>123456788<b>"</b>

**Comment by bigludo7** [comment]
Hello @gregory1g 
The change is not on the notification event but on the subscription resource.
Now that the PR has been merged you'll find the detail [here](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#121-subscription).
