### ISSUE TITLE
Swap Notification example list phoneNumber value without quotes 

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#113]
**Problem description**
event example included in "https://github.com/camaraproject/SimSwap/blob/main/code/API_definitions/sim-swap-notification-subscription.yaml" use phoneNumber without quotes (phoneNumber: +123456788), should be: 
phoneNumber: "+123456788"

----------------
examples:
    SWAPPED:
      value:
        id: "123655"
        source: supertelco.notificationSendServer12
        type: org.camaraproject.sim-swap.v0.swapped
        specversion: "1.0"
        datacontenttype: application/json
        data:
          phoneNumber: +123456788
          subscriptionId: 2ghy-55gg-7iup-yuo9
        time: 2023-01-18T13:18:23.682Z

    SUBSCRIPTION_ENDS:
      value:
        id: "123658"
        source: supertelco.notificationSendServer12
        type: org.camaraproject.sim-swap.v0.subscription-ends
        specversion: "1.0"
        datacontenttype: application/json
        data:
          phoneNumber: +123456789
          terminationReason: SUBSCRIPTION_EXPIRED
          subscriptionId: 2ghy-55gg-7iup-yuo9
          terminationDescription: subscription expire time reached
        time: 2023-01-19T13:18:23.682Z

--------------

**Comment by bigludo7** [comment]
Fixed with #111
