### ISSUE TITLE
Is SimSwap included in Fall Meta Release

### ISSUE THREAD

**Issue by MarkCornall** [camaraproject/SimSwap#114]
**Problem description**
Sim swap is possibly the most deployed api but does not appear in the meta release tracking page https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24 

**Expected action**
Is this correct or an oversight? I would expect it to be included

**Comment by bigludo7** [comment]
Hi @MarkCornall 
Yes we have to do the page for SIM Swap. Will do.

I'm more mitigated for SIM Swap subscription. I'm not sure we have already sandbox version. wdyt?
@fernandopradocabrillo  may I ask you for next call as I will be off to check with the team if we want SIM Swap subscription to be part of this meta release? for my perspective no hurry on this one.

**Comment by bigludo7** [comment]
Hi @MarkCornall,
As Sim Swap [is part of the release](https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24) may we close this issue?
Thanks

**Comment by bigludo7** [comment]
Closed as sim swap part of the release
