### ISSUE TITLE
Revisit defined errors

### ISSUE THREAD

**Issue by fernandopradocabrillo** [camaraproject/SimSwap#119]
**Problem description**

We currently have a couple errors that either don't have a real use case or are not align with the rest of the CAMARA APIs.

1. Error 409 -> what is the usecase for this error? I don't think we have one, maybe we should remove it for the v0.5.0
2. Error 404 SIM_SWAP.UNKNOWN_PHONE_NUMBER-> This is the only API where we have a specific error to cover that the phone number doesn't belong to the Operator. I propose to remove it and include this case in the generic 404 NOT_FOUND for consistency.

**Expected behavior**

1. Error 409 -> being removed from the spec
2. Error 404 SIM_SWAP.UNKNOWN_PHONE_NUMBER -> being removed from the spec and included in generic 404 NOT_FOUND

**Comment by gregory1g** [comment]
According to https://github.com/camaraproject/Commonalities/pull/233 the API must issue 403 - INVALID_TOKEN_CONTEXT when msisdn provided in the payload does not match msisdn extracted from the access token.
This must be added to SimSwap definition as well (currently the only defined 403 case is "Phone number cannot be deducted from access token context")
