### ISSUE TITLE
Portability Events / SIMCARD Activation on SIM SWAP CAMARA API

### ISSUE THREAD

**Issue by cbalbino-infobip** [camaraproject/SimSwap#120]
Hello folks, how are you doing?
I´d like to bring one question here regarding portability events, for example, if CAMARA standard, considers portability events as sim swap event.
I haven´t find out anything related to that in documentation, not sure if you guys have already discussed that, anyhow, there´s one question regarding activation of a new SIMCARD, for example, would it be considered a Sim Swap event?
For example, if I´ve just activated a new SIMCARD on a MNO, if a send a request to the retrieve-date API, would it return to me true or false? 
I know that in case it´s true, if I send the same request on retrieve-date, it would return me the exact sim-swap date as the activation of this new SIMCARD has been activated recently.
Is there some definition from GSMA to define if it should be considered or not? Or it simply can be something to be discussed with the MNOs?
Thank you very much and hope to hear back from you!

**Comment by hdamker** [comment]
@cbalbino-infobip seems that my transfer and your closure happened at the same time. Feel free to reopen if you want to have feedback from the SimSwap sub project.

**Comment by cbalbino-infobip** [comment]
I´d like to remove this thread from here, is it possible? I don´t see any option

**Comment by hdamker** [comment]
@cbalbino-infobip ok, I will delete it.
