### ISSUE TITLE
Authorization and Authentication text was updated in IdentityAndConsentManagement v0.2.0

### ISSUE THREAD

**Issue by hdamker** [camaraproject/SimSwap#133]
**Problem description**

https://github.com/camaraproject/SimSwap/blob/80018e6f7ddd778ddd9b8cf53525501d65eb7e6b/code/API_definitions/sim_swap.yaml#L37 has the previous text but was updated in ICM v0.2.0-rc.1

**Expected behavior**

Text get replaced by the latest text, best the one from upcoming r0.2.0-rc.2 of ICM, which got merged within https://github.com/camaraproject/IdentityAndConsentManagement/pull/186 and is currently available in main branch of ICM.

**Alternative solution**

**Additional context**

Change from https://github.com/camaraproject/IdentityAndConsentManagement/pull/186 is also relevant for sim-swap-subscriptions.

**Comment by fernandopradocabrillo** [comment]
PR created, thanks @hdamker!
