### ISSUE TITLE
Rename the yaml file name

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/SimSwap#138]
**Problem description**
Following discussion in issue [#284](https://github.com/camaraproject/Commonalities/issues/284) in Commonalities, the file name should be `sim-swap.yaml` and not `sim_swap.yaml`.

**Expected behavior**
Change file name

**Alternative solution**

**Additional context**
@hdamker @tanjadegroot  Any change required from Release Management perspective if we change this file name?

**Comment by hdamker** [comment]
> @hdamker @tanjadegroot Any change required from Release Management perspective if we change this file name?

None in `main` from my perspective. But don't forget to update all the links within CHANGELOG, README, and Checklist within the next release PR (for r1.2 with API Version 1.0.0). r1.1 is still consist, so no challenge here.

**Comment by bigludo7** [comment]
Thanks @hdamker 
Will wait next team meeting this Thursday (Aug 22th) to get team approval and then will proceed accordingly.
