### ISSUE TITLE
sim-swap-subscriptions definition should be excluded from "r1.1" sources

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#142]
**Problem description**
r1.1 is a stable version of the SinSwap API.
The 1.X version and quality is applied to all endpoints included in the tagged commit.
sim-swap-subscriptions end point did not reach 1.X level yet, however it is included in the tagged commit: https://github.com/camaraproject/SimSwap/blob/r1.1/code/API_definitions/sim-swap-subscriptions.yaml

**Expected behavior**
remove sim-swap-subscriptions.yaml from "r1.1" branch, but keep it in master. This will allow the group to decide later (after the September release) if subscription API will be tracked together with the "request" API or separately (as a subproject.

**Comment by hdamker** [comment]
@gregory1g In principle I agree that it would be better to have the two APIs in different API repositories (a Sub Project can have multiple API Repositories now). 

But be also aware that the number of the release tag (r1.1) is independent of the versions of the API(s) contained within the release. That's the release notes are clearly stating:

> This release contains the definition and documentation of
> 
> Sim Swap API 1.0.0-rc.1
> Sim Swap Subscriptions v0.1.0-alpha.1
> The API definition(s) are based on
> 
> Commonalities v0.4.0
> Identity and Consent Management v0.2.0

But I agree that it is unfortunate to have an alpha version in the release.

**Comment by gregory1g** [comment]
The last time this was discussed, the agreement was: we want to include check/retrieve API to the Meta release, but not subscription API.
If this is still the case, we should better remove subscription yaml from the tagged commit (this workaround was also discussed)

**Comment by bigludo7** [comment]
I'm fine to remove the subscription alpha version from this meta release.
My only issue is to manage this within our release management process.

Do I have to:

1. Store the subscription yaml 'somewhere', 
2. Remove it to our repo (as the checklist related to this API and readme & changelog part for this API, 
3. Craft the M4 release (without all elements related to sim swap subscription) . 
4. Later we add another specific repo for sim swap subscription and I contribute back the yaml.

**Comment by fernandopradocabrillo** [comment]
The problem I see here is that we don't use release branches anymore, that would solve the issue by simply removing the files from the branch.
For me it's also okey if we don't include the subscriptions in the release, but keeping it doesn't really affect the state of the sim swap API and we save a lot of inconvenience as @bigludo7 stated above...
It is pretty clear that the subscriptions are in an alpha state and should be considered like that, if we want to decouple it we should separete in a different repo, but at this stage..

**Comment by hdamker** [comment]
@bigludo7 @fernandopradocabrillo  If you want to omit the sim-swap-subscriptions.yaml from the public release of the SimSwap repository (which I can understand), it should be quite easy:

> 1. Store the subscription yaml 'somewhere' (in a dedicated branch)

There is no need for that. You have already the tag r1.1 which includes the sim-swap-subscriptions.yaml 0.1.0-alpha.1 version ... you can always refer back to this release tag (it's not a branch, but pointing to a dedicated commit which will "forever" contain this API version).

> 2. Remove it to our repo (as the checklist related to this API and readme & changelog part for this API,
> 3. Craft the M4 release (without all elements related to sim swap subscription) .

I would say that these two steps can even be done together within the release PR for the public release (M4), as you have anyway to touch all these files in the PR. Delete the files related to sim-swap-subscriptions from main, update the README & CHANGELOG accordingly and you are done. 

I would just add a one-line note within the CHANGELOG release notes of r1.2 that sim-swap-subscriptions.yaml is only available as an alpha version and within the r1.1 pre-release, but is not included in this public release.

That would also fit to the [meta-release status page](https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24), as the release tracker for sim-swap-subscriptions was never labeled for the Fall24 release and therefore does not show up.

> 4. Later we add another specific repo for sim swap subscription and I contribute back the yaml.

That would be most probably the best ... the CHANGELOG of this new repository can then start exactly with a link to the r1.1 of the SimSwap repository. 

BTW: was sim-swap-subscriptions raised as an enhancement issue within the API Backlog Working Group? It would be a formal thing, but helpful for the repository creation.

**Comment by hdamker** [comment]
sim-swap-subscriptions is now part of the releases including test definition, so this issue can be closed, right?

**Comment by bigludo7** [comment]
sim-swap-subscriptions is now part of the release :)
