### ISSUE TITLE
Obsolete/wrong statement in API description that "either one or both endpoints could be implemented"

### ISSUE THREAD

**Issue by hdamker** [camaraproject/SimSwap#144]
**Problem description**

The API description contains (still?) the sentence:

> Depending on the network provider implementation, legal enforcement, etc... either one or both endpoints could be implemented.

But none of the both endpoints has 501 as valid response defined, and my understanding is that the design of the responses is now done in a way that every network provider can implement both endpoints, and must do so if offering the API.

**Expected action**

Delete the sentence from the description.

**Additional context**

**Comment by gregory1g** [comment]
I recall that when I raised this question (a long time ago) the answer from Dawid was that  MNO really may implement only one endpoint to be camara compliant. And I do not recall any changes here. 

So, you are right, we should either remove the remark and enforce both end points or introduce 501.

**Comment by hdamker** [comment]
> I recall that when I raised this question (a long time ago) the answer from Dawid was that MNO really may implement only one endpoint to be camara compliant. And I do not recall any changes here.

There was some more recent discussion, even in the TSC, cf. https://wiki.camaraproject.org/display/CAM/2024-07-18+TSC+Minutes
