### ISSUE TITLE
Test definitions - linting results 

### ISSUE THREAD

**Issue by rartych** [camaraproject/SimSwap#149]
**Problem description**
While testing linting rules for Gherkin the following output was produced for _checkSimSwap.feature_

```
  18    Multiple empty lines are not allowed                                        no-multiple-empty-lines
  40    Scenario name is already used in: checkSimSwap.feature:32                   no-dupe-scenario-names
  67    Trailing spaces are not allowed                                             no-trailing-spaces
```
For _retrieveSimSwapDate.feature_
`  28    Multiple empty lines are not allowed                                                no-multiple-empty-lines
`

**Expected behavior**

❗ Line number 9 in both files should be marked as comment - otherwise it is **syntax error**.

The most of issues are related to formatting.
But the optional scenario title is indeed duplicated in lines 32 and 40.

It should be considered to change the filenames of test definitions to kebab-case.

**Alternative solution**

**Additional context**

**Comment by bigludo7** [comment]
Thanks @rartych 
done !

**Comment by rartych** [comment]
Closing as fixed in release PR https://github.com/camaraproject/SimSwap/pull/148
