### ISSUE TITLE
Issue with @check_sim_swap_6_no_sim_swap scenario

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/SimSwap#154]
**Problem description**
Doing the test I have an issue with this scenario:

```
  @check_sim_swap_6_no_sim_swap
  Scenario: Check that the response shows that the SIM has not been swapped
    Given the request header "Authorization" is set to a valid access token from which a phone number connected to the Operator's network can be deducted
    And the SIM for this phone number has never been swapped
    When the request "checkSimSwap" is sent
    Then the response status code is 200
    And the value of response property "$.swapped" == false
```

Indeed, we consider that: `New subscription is considered as a SIM swap as well` in the yaml so for the test must be reworked accordingly.
Suppose a new line was activated Oct8th at 4pm
If I make a query Oct9th at 4pm

- I expect true if `maxAge` is set to 36
- I expect false if `maxAge` is set to 12

**Expected behavior**
First get @fernandopradocabrillo feedback :)

**Alternative solution**

**Additional context**

**Comment by fernandopradocabrillo** [comment]
@bigludo7 you are right, this test does not cover all the cases, I'll create a PR to detail it a bit more and include a new one to cover both cases.
1. No swap when providing maxAge
2. No swap when using default maxAge

Thanks for bringing it up! I'll update the WIP device swap accordingly
