### ISSUE TITLE
Change meeting frequency - from every 2 weeks to every 4 weeks

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/SimSwap#163]
**Problem description**
Change meeting frequency - from every 2 weeks to every 4 weeks

**Expected action**
Latest 2 meetings cancelled because too few update. But good to keep a sync.
Ask for @wrathwolf to change the Zoom Invitation.

**Additional context**

**Comment by fernandopradocabrillo** [comment]
@wrathwolf @bigludo7 
the next meeting should be on oct 31st and the next one on nov 28th right?

**Comment by bigludo7** [comment]
Next meeting for sure Oct 31th and if no objection from the team next one will be Nov 28th
