### ISSUE TITLE
broken links in MC APT API description (files were most probably relocated?)

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#19]
https://github.com/camaraproject/SimSwap/blob/main/documentation/API_documentation/MobileConnect/MobileConnectATP.md has a chapter "ATP API details". The chapter contains 2 links:
"
YAML files:
[MC](https://github.com/camaraproject/SimSwap/blob/main/documentation/API_documentation/MobileConnect/MC_ATP.yaml)
[OAS](https://github.com/camaraproject/SimSwap/blob/main/documentation/API_documentation/CAMARA/checkSimSwap-v0.3.0.camara.swagger.yaml)
"
none of the files exist.
The first is, most probably: https://github.com/camaraproject/SimSwap/blob/main/code/API_definitions/MobileConnect/MC_ATP.yaml
The second - https://github.com/camaraproject/SimSwap/blob/main/code/API_definitions/CAMARA/checkSimSwap-v0.3.0.camara.swagger.yaml

**Comment by DT-DawidWroblewski** [comment]
Created PR #22 to update this md. Thx for heads up!

**Comment by DT-DawidWroblewski** [comment]
fixed
