### ISSUE TITLE
MSISDN in the input and IDY.24

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#25]
https://github.com/camaraproject/SimSwap/blob/c317b025fe1fd121cc25219ab9244471fe234c9d/code/API_definitions/MobileConnect/MC_ATP.yaml#L94
IDY.24 does not specify an MSISDN as a required parameter (inn a header). As far as I understand, IDY.24 implements OIDC openid/userinfo endpoint, what means that user identity is extracted from access/identity tokens.

**Comment by DT-DawidWroblewski** [comment]
Hi @gregory1g !

for MC Account Takeover Protection we're following additional spec that utilize OAUTH2.0 client credentials (spec is a result of joint collaboration between customers & MNOs)

[please see IDY.56.1 for reference](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.56.1-Mobile-Connect-Client-Credentials-for-Attributes-Configuration-A.pdf)

MSISDN comes inside **User-ID** header that is a part of /userinfo request along with **User-ID-Type**.

[please see Table 1 @IDY.56.1 for reference](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.56.1-Mobile-Connect-Client-Credentials-for-Attributes-Configuration-A.pdf)

MC specs are build on OIDC, although were adopted MC ATP (with sim swap) to work with OAUTH2.0 client credentials grant, that gives more value to our customers (especially when it comes to speed/latency & easy of use).

**Comment by gregory1g** [comment]
According to my understanding IDY.56 described token request API. But afterwards this is not needed anymore.

>MC specs are build on OIDC, although were adopted MC ATP (with sim swap) to work with OAUTH2.0 client credentials grant, that gives more value to our customers (especially when it comes to speed/latency & easy of use).

But it looks like that this extension makes it MC and OIDC incompatible.

Let's discuss this, if possible

**Comment by bigludo7** [comment]
Link to https://github.com/camaraproject/NumberVerification/issues/35

**Comment by DT-DawidWroblewski** [comment]
> According to my understanding IDY.56 described token request API. But afterwards this is not needed anymore.
> 
> > MC specs are build on OIDC, although were adopted MC ATP (with sim swap) to work with OAUTH2.0 client credentials grant, that gives more value to our customers (especially when it comes to speed/latency & easy of use).
> 
> But it looks like that this extension makes it MC and OIDC incompatible.
> 
> Let's discuss this, if possible

The most common way MNOs serve GSMA Mobile Connect ATP is with [Client Credentials Profile](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.56.2-Mobile-Connect-Client-Credentials-for-Attributes-Configuration-B.pdf). However, IDY.24 defines OpenID Connect & CIBA (there is no reference to IDY.56 currently) as solutions to deliver the service, with CIBA recommendation, as for this specific service request/response should take place "behind the scenes" to avoid visibility to potential attacker.

Let's discuss :)
