### ISSUE TITLE
MC ATP and boolean output

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#26]
https://github.com/camaraproject/SimSwap/blob/545be2cdf1a32ad15974a3e10c3e7f0fd2d3e8e7/code/API_definitions/MobileConnect/MC_ATP.yaml#L109

IDY.24 clearly specifies that output contains timestamps not booleans. Moreover, it looks like, there is no input parameter which defines if dates or booleans must be returned and what time interval for which the check must be done. And introducing of such parameter could mistmatch OIDC alignment of the API

**Comment by bigludo7** [comment]
Link to https://github.com/camaraproject/NumberVerification/issues/35

**Comment by DT-DawidWroblewski** [comment]
"the boolean flavor" of MC ATP came out during discussions with data privacy teams and our customers. It is not currently mentioned in MC Specs as it is MC ATP enhancement in a sense that delivers additional business logic for standard timestamp
