### ISSUE TITLE
POST for openid/userinfo is not compatible with OIDC

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#27]
https://github.com/camaraproject/SimSwap/blob/c317b025fe1fd121cc25219ab9244471fe234c9d/code/API_definitions/MobileConnect/MC_ATP.yaml#L75

Correct me if I'm wrong, but IDY.24 implements OIDC openid/userinfo API, not juts coincidentally uses the same endpoint.
OIDC describe this endpoint as a GET API. Using POST here is incompatible with OIDC and breaks REST design principles ("POST UserInfo" looks like an update/create API).

**Comment by bigludo7** [comment]
Link to https://github.com/camaraproject/NumberVerification/issues/35
