### ISSUE TITLE
MC Yaml or SIM Swap YAML 

### ISSUE THREAD

**Issue by psidana1983** [camaraproject/SimSwap#30]
Hi Team ,

I could see that few of the APIs are having 2 YAML file, one corresponding to MC and the other corresponding to CAMARA . I want to understand out of the provided 2 YAMLs which one should we use to be CAMARA Complaint. 

In one of the API discussion the SPOC told me that  MC version is the existing productive one, but this is not compliant with CAMARA commonalities. So CAMARA is working on a new harmonized version. As soon as this is defined it shall be implemented and replace the MC one. Then the MC one can be deleted.

If above is true then shall i continue using CAMARA yaml file to be CAMARA Complaint  ? Please confirm .

**Comment by ShutingQing** [comment]
Interested in this question too.

**Comment by gregory1g** [comment]
Removal of MC version from Camara request is currently forwarded to "Commonalities" team.
Check: https://github.com/camaraproject/WorkingGroups/issues/200
