### ISSUE TITLE
Move meeting from 18 of May to another day?

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#33]
https://github.com/camaraproject/SimSwap/blob/c317b025fe1fd121cc25219ab9244471fe234c9d/documentation/MeetingMinutes/README.MD?plain=1#LL55C1-L55C13

18 of May 2023 is a public holiday in some European countries.
It would be good to move the meeting to another day.

Sorry for using an issue for this question, but I cannot post in a group "chat" (because "Your subscription has not yet been approved.")

**Comment by ShutingQing** [comment]
So much admire European friends, you have so many holidays, really. 

Shall we have a meeting tomorrow on Tuesday instead?

**Comment by DT-DawidWroblewski** [comment]
Meeting takes place on 1st of June 2023 (Thursday)
