### ISSUE TITLE
Glossary Alignment

### ISSUE THREAD

**Issue by monamok** [camaraproject/SimSwap#41]
**Problem description**

A new PR https://github.com/camaraproject/SimSwap/pull/40 is opened to handle these points:

- The parameters names were indicated in [Glossary](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md) in order to be unified in the whole CAMARA project. This PR is to change msisdn to phoneNumber. 
- Also the example of phoneNumber was change to make it more clear that country code must be included.
- Some typo fixes and minor changes were included

The label must be changed to **fix** but it seems I don't have permissions to edit it.

**Comment by monamok** [comment]
I didn't include documentation update in the PR. Once it's approved and merged we should open a new PR to embed the updated documentation in the API Spec.

**Comment by DT-DawidWroblewski** [comment]
merged...closing
