### ISSUE TITLE
Embedding documentation in CAMARA API spec and decision about documenting authorization methods

### ISSUE THREAD

**Issue by monamok** [camaraproject/SimSwap#42]
**Problem description**

API documentation should be included in API Spec.
Related to: https://github.com/camaraproject/WorkingGroups/issues/164

**Expected action**
We must move the information from here https://github.com/camaraproject/SimSwap/blob/main/documentation/API_documentation/CAMARA/Check_sim_swap_API.md into the API yaml file to be aligned with the guidelines

**Additional context**

Checking the documentation as well as the API spec, for authorization it says that the API considers 2 security models: Three-legged access tokens with dedicated scopes, and OAuth 2.0 client credentials.

@bigludo7 having in mind that this API handles personal information how do you feel about removing OAUTH 2.0 client credentials grant and sticking to 3-legged tokens?

The documentation and API Spec must get updated by this decision.

**Comment by monamok** [comment]
> I'm not completely sure: I've checked what we are doing in Orange and seems that we live with OAUTH 2.0 only for the **check** operation as long as we check that the application requesting use of the api has a fair purpose of using this API.

@bigludo7 in check endpoint we check whether a user's SIM card has been swapped. Asides from purposes, I think this information is classified as personal information and we need user's consent to return that information. That's why I was thinking client credentials wouldn't be enough and we might face auditing problems and access control issues.
So in Orange you don't consider it as personal information?

**Comment by bigludo7** [comment]
@monamok This is personal information but specifically for this API (and for the check) this is delegated  of the application developer onboarding/agreement. We ask/check the rationale to provide this information and the developer sign an agreement that he/she will use it in this context only. Not sure this is a 'target' pattern....so let go for the 3-leg for both operation and we will follow discussion in consent&IdentityManagement project.

**Comment by monamok** [comment]
According to our discussion for the moment we keep both security schemas. It will be aligned to the result of the discussion in consent&IdentityManagement project once it's resolved.
But having in mind that 3-legged is one of the methods, maybe we should consider making phoneNumber input parameter optional as for that mechanism, the number associated to token can be used and there is no need to receive it as input.

What do you think about this point?

**Comment by gregory1g** [comment]
@monamok sounds reasonable. from API design point of view it would be good to describe what should happen if both are provided, because this directly important for privacy protection.

**Comment by monamok** [comment]
> from API design point of view it would be good to describe what should happen if both are provided

@gregory1g I agree. In case the phoneNumber changed to be optional, additionally the documentation must be updated and perhaps some new errors will be defined as well (which I guess we would discuss them). For example we could have these scenarios and just with 3-legged tokens:

- Phone number is not provided and cannot be deducted from access token context.
- Phone number is not provided and the associated phoneNumber to the access token which was used to call the endpoint does not match the provided phoneNumber and does not have permission to access the provided phoneNumber either 
- ...

@bigludo7 if you prefer to wait, we leave this issue on-hold. I just wanted to point out that even if both methods are allowed in the end, for 3-legged tokens phoneNumber is not explicitly necessary and we could remove required but no problem with waiting for the result. The issue will serve for tracking. 

Thank you.
