### ISSUE TITLE
GSMA OGW Product WS - Subscription/notification mechanism for SIM SWAP formal request

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/SimSwap#47]
Problem description
Formal inclusion of the GSMA OGW Product WS request to include Subscription/notification mechanism as part of OGW services.

https://github.com/camaraproject/Commonalities/issues/8#issuecomment-1642419272

Possible evolution
SIM SWAP API, as many other current APIs, may be enhanced by a subscription mechanism that will enable different use cases, e.g.:

- Antifraud mechanism may require being notified by the operator when a SIM is affected by a swap procedure, implementing different mechanisms to avoid fraud (e.g., warm or confirm with the user).

The proposal includes examples or proposal for input-outputs of such mechanism, to be discussed and aligned with the current service API.

Alternative solution
N/A

Additional context
More details included in the formal request file, attached
[Camara Submission - Subscription_Notifications v2.docx](https://github.com/camaraproject/SimSwap/files/12098247/Camara.Submission.-.Subscription_Notifications.v2.docx)

**Comment by bigludo7** [comment]
As discussed in team meeting Sept 7th

- We agreed that this feature must be added.
- This feature will be managed in the SimSwap API Family.
- We have to decide if we want to have the SimSwap Notification Subscription is the **same** yaml than current one (checkSimSwap.camara.swagger.yaml) or have a **separate** yaml.

@DT-DawidWroblewski  @gregory1g  and @bigludo7 already provided their preference for a distinct yaml as we perceive this as a distinct product.

**Looking for team feedback as it would be great to have decision on this topic for next meeting (Sept 21th) **
