### ISSUE TITLE
Is there an upper limit to max age (POST /check)?

### ISSUE THREAD

**Issue by trehman-gsma** [camaraproject/SimSwap#56]
Hi all,

Apologies if this is not the correct forum for this question or if I am not following the correct Github guidelines. I am asking this on behalf of an Indonesian operator technical group who are mobilizing for CAMARA. 

**Is there an upper limit for maxAge (part of the POST /check input body)?** 

Thanks in advance.

**Comment by gregory1g** [comment]
upper limit is an implementation specific. The implementation must consider legal requirements and can consider technical aspects.
It was agreed to add corresponding remark to the spec description.

**Comment by trehman-gsma** [comment]
Thank you @gregory1g. I will relay this to the Indonesia operator group and I will close this issue.
