### ISSUE TITLE
Remove MSISDN from request body

### ISSUE THREAD

**Issue by fernandopradocabrillo** [camaraproject/SimSwap#58]
**Problem description**
With the use of 3-legged authorization flow, it is no longer necessary to send the phone number in the request body as it can be obtained from the token.

**Expected behavior**
The MSISDN will be obtained from the 3-legged token.

**Alternative solution**
N/A
**Additional context**
N/A

**Comment by DT-DawidWroblewski** [comment]
Hi @fernandopradocabrillo !

as client credentials is still an option MSISDN has to be passed in a resource request. However, I suggest using HTTP request header to pass the MSISDN value.

**Comment by chrishowell** [comment]
I don't think we can remove the `msisdn` from request, there could very easily be scenarios where the target device (the `msisdn` in the request) is not the same as the authorisation device.

**Comment by fernandopradocabrillo** [comment]
Hi @chrishowell 
In today's meeting we have agreed to leave it as an optional parameter in the request body.
I didn't have the time to update the PR yet
