### ISSUE TITLE
Mobile Connect SIM Swap vs CAMARA Sim Swap

### ISSUE THREAD

**Issue by mikhilsanghvi** [camaraproject/SimSwap#69]
**Problem description**
Apologies if this is not the right forum to ask below question but appreciate if someone can clarify.

How different is SIM Swap solution specified in Mobile connect (/premiumInfo) versus SIM Swap solution specified in CAMARA project. 
Mobile Connect SIM Swap follows a OIDC Authorisation grant. Is there a similar authentication requirement for CAMARA version of SIM Swap or if the CAMARA guideline is to follow Mobile Connect ATP flow to get the access tokens along with MTAP attributes and claims and then have a CAMARA compliant API endpoint to get the SIM change details (specifically invoke POST /retrieve-date instead of GET /premiunInfo)

Thanks in advance!

**Comment by mikhilsanghvi** [comment]
@DT-DawidWroblewski Would you able to throw some light here please. Thank you!

**Comment by DT-DawidWroblewski** [comment]
Hi @mikhilsanghvi !

you mentioned the main difference, which is:
> resource consumption on a dedicated endpoint (Camara) vs common endpoint (Mobile Connect)

Here are some additional:

Mobile Connect ATP is designed to deliver additional attributes within response, i.e.:
|attribute name|usage category|
|:--:|:--:|
|sim_change|REQUIRED|
|is_unconditional_call_divert_active|OPTIONAL|
|is_lost_stolen|OPTIONAL|
|device_change|OPTIONAL|
|account_state|OPTIONAL|

[see spec for reference](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.24-Mobile-Connect-Account-Takeover-Protection-Definition-and-Technical-Requirements-v2.0.pdf)

Camara scope is narrowed to a use case, e.g. _/retireve-date_ delivers sim change date in a response body

In Mobile Connect you can utilize either OIDC or OAUTH2.0 Client Credentials grant. In Camara we recommend to use OIDC (authorization code grant).

In Mobile Connect it is a _scope_ value that triggers business logic on Authorization Server (e.g. mc_atp, mc_kyc_match, mc_vm_match). In Camara it is an endpoint that triggers business logic on Authorization Server.

So as you see, there are API consumption differences, but both MC & Camara delivers the same value (API response) to API consumer.

I hope that helps.

**Comment by mikhilsanghvi** [comment]
Thank you so much @DT-DawidWroblewski for the response. That really helps.

Just a couple of questions around the authorization 

1. The auth code grant in Mobile connect verifies the request based on the MSISDN or PCR and verifies if the user has Mobile connect account (as shown in figure 1 of the [spec](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.24-Mobile-Connect-Account-Takeover-Protection-Definition-and-Technical-Requirements-v2.0.pdf)). I understand now that CAMARA API is free from these flows. Is the understanding correct?
2. > In Mobile Connect it is a scope value that triggers business logic on Authorization Server (e.g. mc_atp, mc_kyc_match, mc_vm_match). In Camara it is an endpoint that triggers business logic on Authorization Server.

    Assuming my understanding in point 1 is correct and as per your comment above, does this mean that the OIDC grant used in CAMARA is free of the MSISDN as loginHint and other attributes and the SP with right credentials can get SIM Swap details for any MSISDN (in request body) with the same access token unlike the Mobile Connect version where a access token can be used to get SIM Swap information of only a specific MSISDN that was used to generate the access token?

**Comment by DT-DawidWroblewski** [comment]
Hi @mikhilsanghvi !

>The auth code grant in Mobile connect verifies the request based on the MSISDN or PCR and verifies if the user has Mobile connect account (as shown in figure 1 of the [spec](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.24-Mobile-Connect-Account-Takeover-Protection-Definition-and-Technical-Requirements-v2.0.pdf)). I understand now that CAMARA API is free from these flows. Is the understanding correct?

Camara focus is around resource definition. You can find more about Camara AuthZ & AuthN concept [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md).

[Camara general statement](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md) about user identity does not limit the usage of PCR or any other identifier, that comes in ID Token _sub_ claim.

>Assuming my understanding in point 1 is correct and as per your comment above, does this mean that the OIDC grant used in CAMARA is free of the MSISDN as loginHint and other attributes and the SP with right credentials can get SIM Swap details for any MSISDN (in request body) with the same access token unlike the Mobile Connect version where a access token can be used to get SIM Swap information of only a specific MSISDN that was used to generate the access token?

whenever user data is involved MSISDN is required in loginhint (CIBA flow), end-user authentication + consent => [see here for details](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#authorization-code-flow-frontend-flow).

BTW - Mobile Connect allows to create access token outside end-user context => see [Mobile Connect Client Credentials for Attributes specification](https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.56.1-Mobile-Connect-Client-Credentials-for-Attributes-Configuration-A.pdf) for details.

**Comment by mikhilsanghvi** [comment]
Hi @DT-DawidWroblewski ,

Thanks for sharing the references.

Since it is recommended to have MSISDN loginhint for the SIM Swap API, would it be worth mentioning that the MSISDN in the loginHint should match the MSISDN received in the CAMARA SIM Swap request body and define appropriate error code when it does not match?

**Comment by DT-DawidWroblewski** [comment]
resolved
