### ISSUE TITLE
Call Center Use Case for SIM Swap

### ISSUE THREAD

**Issue by HuubAppelboom** [camaraproject/SimSwap#81]
There is another use case for SIM Swap data that should be kept in mind when standardising the API.

The use case is that the fraudster, swaps the SIM card and obtains the mobile number of a victim.

When the bank notices a suspicious transaction, they call the victim (but get the fraudster on the phone in stead).  If they would have known the recent sim swap date, they wouldnt make the call.

Note that this can also be the case when the bank is not using SMS 2FA.  We have seen a number of these cases now in NL, and this is the reasons banks have revived interest in Sim Swap data here.

Can we add this use case also to the documentation ?

And can we keep in mind that in this use case, there may be no interaction with the device of the user ?

**Comment by gregory1g** [comment]
Can you explain the NL case. Did bank processed suspicious transaction and only then called a customer? How SimSwap will help?  The bank detects SimSwap and does not call the customer - ok, but the "suspicious transaction" is already processed.

If the bank calls the customer before allowing suspicious transaction, this is usually done by a robocall - and is basically a voice OTP, right?

**Comment by HuubAppelboom** [comment]
In these cases the bank detected suspicious activity in the account of the (small business) users, and suspended the transactions to have things clarified. 

They didn't want to clarify how they detected it, but banks use thee days riks engines that analyse all activites.  In case a transaction is out of the regular behaviour, it can be flagged and (temporariliy halted).  For example, if there is a combination of an increase money transfer limits, and all of a sudden high value transactions close to the limit towards a bank account abroad that has never been used before.  Another risk factor could be that the bank detects that Remote Access Tooling has been installed on a victims device, or that the bank account is all of sudden been accessed form a strange IP address.

In these cases the transactions are halted, and the fraud department of the bank makes a manual outgoing call to the victim, and go through a series of check questions to see what is going and everyting is all right.  The SIM Swap detection should be added to this outgoing call to warn the fraud department that they may be talking to the fraudster (and who claims everything is normal).

In general, Sim Swap Fraud is a form of spear phishing, in which victims have been tracked for months. Usually it starts with taking over email accounts, and following all email traffic.  From this they build a profile (like what banks they do business with, whether they have bitcoin accounts etc), and start targeting these accounts.  In this process the scammers may have already taken over a number of account, but have not done anything because they think there is more to be collected. The fraudulent SIM swap usually follows quite late in this process, because they know it will cause alarm bells to go off.

**Comment by gregory1g** [comment]
So, they hold the transaction - got it.

regarding the general way how SimSwap attack is done. We have seen different statistic and different ways SimSwap attack is implemented in different regions.
@HuubAppelboom, do you have links to researches which show that a personalized, well prepared attach is the main usage for SimSwap fraud?

**Comment by HuubAppelboom** [comment]
A good article on Sim Swap fraud can be found here (https://www.europol.europa.eu/media-press/newsroom/news/ten-hackers-arrested-for-string-of-sim-swapping-attacks-against-celebrities). 

Please note there can be large differences between countries, depending opportunity and reward for fraudsters, which vary per country.

**Comment by gregory1g** [comment]
> Please note there can be large differences between countries, depending opportunity and reward for fraudsters, which vary per country.

This was exactly my point.  afaik, in some cases it is used more massive without "victims have been tracked for months".

**Comment by HuubAppelboom** [comment]
> > Please note there can be large differences between countries, depending opportunity and reward for fraudsters, which vary per country.
> 
> This was exactly my point. afaik, in some cases it is used more massive without "victims have been tracked for months".

Yes, but in most (if not all) cases, the user has already been phished previously for a password, which the fraudster also needs to have.  And in countries where SIM Swap Fraud is hard to do, they first make a good analysis (whether the victim has sufficient funds) before they put in the effort.

**Comment by DT-DawidWroblewski** [comment]
Closing
