### ISSUE TITLE
Make response properties required

### ISSUE THREAD

**Issue by fernandopradocabrillo** [camaraproject/SimSwap#96]
**Problem description**
Make response properties "latestSimChange" and "swapped" required since they will always be returned

**Comment by bigludo7** [comment]
Hello @fernandopradocabrillo 
Are we sure for `latestSimChange` as this is not the outcome of https://github.com/camaraproject/SimSwap/issues/16 ?

My apologies if I missed a conversation within the team to agreed on this. Not a blocker for me but wanting to be sure we have agreement.
cc @trehman-gsma

**Comment by fernandopradocabrillo** [comment]
Hi @bigludo7 
I assume this was the agreed outcome since we haven't had any new update and Toyeeb's summary pointed in that direction. I missed that meeting but there seemed to be a consensus.
From TEF we have actually implement in this direction using the null as preferred option.

**Comment by bigludo7** [comment]
Hello @fernandopradocabrillo 
But option 2 of the #16 is:

```
# 2 - an empty body returned because latestSimChange is an optional attribute
{

}
```

I'm fine to remove this option but probably let's wait a formal discussion in next meeting - wdyt?

**Comment by fernandopradocabrillo** [comment]
Hello @bigludo7 
Sure, let's discuss on the next meeting. Maybe I was too fast in assuming the outcome, the empty body option is feasable for us too, I just thought it was out of the table.
