### ISSUE TITLE
Add links to user friendly API viewers directly in the readme file 

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/SimSwap#99]
Readme file of [DeviceLocation ](https://github.com/camaraproject/DeviceLocation?tab=readme-ov-file)API project includes links which open API specification in Swagger Editor and in ReDoc viewer.
This is a really helpful and easy to add "feature".  

Suggestion: add similar links for SimSwap API as well.

**Comment by fernandopradocabrillo** [comment]
@gregory1g but we already have this don't we?

<img width="644" alt="image" src="https://github.com/camaraproject/SimSwap/assets/33178221/dc593e07-2cbe-4d07-847e-97fcaac5a207">

**Comment by gregory1g** [comment]
you are right. just close this issue
